### ISSUE TITLE
How to set multiple conditional rules

### ISSUE THREAD

**Issue by alexstulov** [ritchieanesco/json-schema-yup-transform#12]
There are an example with single conditional rule. Is there a way to set more than one condition?

"Is" and "then" keys must be unique. So the only option I see is pass conditions as an array. But when I do so, rules not applied.

    if: [
        {
          properties: {
              country: {
                const: "Australia"
              }
          }
        }
    ],
    then: [
        {
          properties: {
              residencyYears: {
                  type: "number",
                  minimum: 12
              }
          },
          required: ["residencyYears"]
      }
    ]

**Comment by ritchieanesco** [comment]
@alexstulov,

You would need to use the [`allOf`](http://json-schema.org/understanding-json-schema/reference/combining.html#allof) property. Unfortunately, this is not available in this library... yet. I will be looking at introducing it when i have a bit more time but always open to contributions to the source code.

**Comment by adanielyan** [comment]
Unless I am wrong, I believe the #45 doesn't solve this particular issue. It is not about having multiple conditions that should pass in order for a validation to kick in, but it's about having multiple conditions for validating multiple properties. E.g. you may want to make `residencyYears` required if `country ` is "Australia", and also make the `otherOccupation` required if `occupation` is "Other". How will you do it if you can only have one `if` key and one `then` key and they are not related in any way. If these keys were encapsulated in a parent array of objects then it would be possible. Something like this:

```JS
{
  ...
  conditions: [
    {
      if: [
        {
          properties: {
            country: {
              const: "Australia",
            },
          },
        },
      ],
      then: [
        {
          properties: {
            residencyYears: {
              type: "number",
              minimum: 12,
            },
          },
          required: ["residencyYears"],
        },
      ],
    },
    {
      if: [
        {
          properties: {
            occupation: {
              const: "Other",
            },
          },
        },
      ],
      then: [
        {
          properties: {
            otherOccupation: {
              type: "string",
            },
          },
          required: ["otherOccupation"],
        },
      ],
    },
  ];
}
```
