### ISSUE TITLE
Import statement in examples is not correct

### ISSUE THREAD

**Issue by ost-ing** [ritchieanesco/json-schema-yup-transform#13]
Hey, thanks for writing this library. I'm trying to integrate it into my project using Formik, and noticed that the import seems incorrect.

`import { convertToYup } from 'json-schema-yup-transformer';`

gives me the compilation error: `Object(...) is not a function`.

Adjusting the import to: `import convertToYup from 'json-schema-yup-transformer';`  and then using this works:

```
import convertToYup from 'json-schema-yup-transformer;

const yupValidation = convertToYup(jsonSchema);

// Then use with Formik
```

Thanks for this library, keep up the good work.

**Comment by ost-ing** [comment]
Why was this closed with no discussion? This happens using both storybook and nextjs.

**Comment by ritchieanesco** [comment]
> Why was this closed with no discussion? This happens using both storybook and nextjs.

Apologies. Thanks for picking this up.

**Comment by ritchieanesco** [comment]
Updated code examples (26d584bafe3f84f92f1098c8f415069f680ad95c).
