### ISSUE TITLE
stringify-object package should be a dependency

### ISSUE THREAD

**Issue by ost-ing** [ritchieanesco/json-schema-yup-transform#14]
When adding this library to a nextjs application, compilation fails:

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'stringify-object' in '.../webapp/node_modules/json-schema-yup-transformer/dist/yup/addMethods'
```

If this is a dependency it should be added as such

**Comment by ritchieanesco** [comment]
Fixed here 13001a8d5b22abfcba7228d05d6e68215ecf517a . Available in v1.57
