### ISSUE TITLE
String type with enum keyword is not allowed to have value undefined

### ISSUE THREAD

**Issue by adriandotta-infotrack** [ritchieanesco/json-schema-yup-transform#15]
Having this schema:
`const schema= {
  title: 'Form',
  type: 'object',
  properties: {
    id: {
      type: 'string',
      title: 'id',
      enum: ['1', '2', '3'],
    },
  },
};`

After submit I'm getting the error:
"Id does not match any of the enumerables"

Forcing me to select a value from my select component.

Only works if I add the default keyword on it.

It that happened to anyone?
Thanks!

**Comment by ritchieanesco** [comment]
@adriandotta-infotrack are you able to provide a code snippet or replicate in code sandbox?

**Comment by adriandotta-infotrack** [comment]
Hey @ritchieanesco! Thanks for the reply :)
https://codesandbox.io/s/react-playground-forked-5qjyr?file=/index.js

here it is ;)

**Comment by ritchieanesco** [comment]
@adriandotta-infotrack you seem to be trying to validate the json schema itself. The json schema is used to generate a rules object using the yup framework. Using your example, the `json-schema-yup-transform` will convert enumerated values in json schema to the following yup schema
```
Yup.object().shape({
  name: Yup. mixed().oneOf(["Item 1", "Item 2", "Item 3"])
})
```
This schema would then be able to validate the following key value pair structure:

```
{
  name: "" 
}
// returns invalid

{
  name: "Item 1" 
}
// returns valid

```

Example usage:
```
const schemaInValid = {
  type: "object",
  $schema: "http://json-schema.org/draft-07/schema#",
  $id: "example",
  title: "Example",
  properties: {
    name: {
      type: "string",
      enum: ["Item 1", "Item 2", "Item 3"]
    }
  }
};
const yupschema = convertToYup(schemaInValid);
await yupschema.isValid({name: "Item 1"}); //returns true
```

**Comment by adriandotta-infotrack** [comment]
Understood :) I just created a JsonForm from scratch and I'm using this library. But my problem was when I use a select I can not have an empty or undefined value, so is forcing me to give it a default value for this reason `.oneOf(["Item 1", "Item 2", "Item 3"])`

Thanks a lot for your reply! ;)

**Comment by ritchieanesco** [comment]
Which I guess is working as intended, so from my understanding you want the ability to accept falsey values but not be included in the enum?

**Comment by adriandotta-infotrack** [comment]
Yes, it is :) My question would be if I add the required attr, that's ok I have to select a value, but if not, is there a way to have that enum attr and not be required? :O

**Comment by julioxavierr** [comment]
+1.

I'm having the same issue with `enum`, the validation should allow me to not pass the value if it's not required.

**Comment by julioxavierr** [comment]
As a workaround,  I'm adding `undefined` as one of the elements of the enum array in case it's not required:

```ts
        properties: {
          period: {
            type: 'string',
            // @ts-ignore
            enum: ['Day', 'Month', 'Year', undefined]
          }
        }
```

But it would be awesome to have it fixed though

**Comment by ritchieanesco** [comment]
@adriandotta-infotrack @julioxavierr 

For future reference you can set multiple types:

```ts
const schema = {
  type: "object",
  $schema: "http://json-schema.org/draft-07/schema#",
  $id: "example-default-error-messages",
  title: "Example of default error messages",
  properties: {
    id: {
      type: ["string", "null"],
      title: "id",
      enum: ["1", "2", "3"]
    }
  }
};
const yupschema = convertToYup(schema);
let isValid = yupschema.validateSync({
  id: null
});
// => true

isValid = yupschema.validateSync({
  id: "4"
});
// => false
```
Code sand box: https://codesandbox.io/s/lucid-meitner-22upp?file=/src/index.js
