### ISSUE TITLE
Message of array objects

### ISSUE THREAD

**Issue by gustavodecarli** [ritchieanesco/json-schema-yup-transform#25]
Hello, in me json schema, array of objects.

"items": {
			"description": "oooo",
			"type": "array",
			"items" : {
				"type" : "object",
				"properties" : {
					"importe": {
						"description": "oooo",
						"type": "number",
						"nullable": false
						},
					"descripcion": {
						"description": "oooo",
						"type": "string",
						"nullable": false
						},
....

Don't take the messages errors , 

"items": [{
			"importe": {
					"required": "El campo ${path} es requerido"
				},
			"descripcion": {
					"required": "El campo ${path} es requerido"
				}
			}]

It's a bug , you cant help me.
Thk

**Comment by gustavodecarli** [comment]
**I found that if the array name is "items", it doesn't recognize the associated message**

Example :

import convertToYup from "json-schema-yup-transformer";

const schema = {
  type: "object",
  $schema: "http://json-schema.org/draft-07/schema#",
  $id: "example-default-error-messages",
  title: "Example of default error messages",
  properties: {
    items: {
      type: "object",
      nullable: true,
      properties: {
        name: {
          type: "string"
        }
      },
      required: ["name"]
    }
  }
};

// set default error message for type of string

const config = {
  errors: {
    defaults: {
      string: "Custom error message"
    },
    items: {      
      name: {
        required: "My Message validacion"
      }      
    }
  }
};

// check validity
const yupschema = convertToYup(schema, config);
let errorMessage;

try {
  errorMessage = yupschema.validateSync({
    
  });
} catch (e) {
  errorMessage = e.errors[0];
}

console.log(errorMessage)

**Comment by gustavodecarli** [comment]
The same for array attribute width name "items"

import convertToYup from "json-schema-yup-transformer";

const schema = {
  type: "object",
  $schema: "http://json-schema.org/draft-07/schema#",
  $id: "example-default-error-messages",
  title: "Example of default error messages",
  properties: {
    items: {
      type: "array",
      items: {
          type: "object",          
          properties: {
            name: {
              type: "string"
            }
          },
          required: ["name"]
      }
    },
  }
};

// set default error message for type of string

const config = {
  errors: {
    defaults: {
      string: "Custom error message 2"
    },
    "items": {      
      "name": {
        "required": "Error message"
      }      
    }
  }
};

// check validity
const yupschema = convertToYup(schema, config);
let errorMessage;

try {
  errorMessage = yupschema.validateSync({datos: [{}]    
  });
} catch (e) {
  errorMessage = e.errors[0];
}

console.log(errorMessage)

**Comment by ritchieanesco** [comment]
> **I found that if the array name is "items", it doesn't recognize the associated message**
> 
> Example :
> 
> import convertToYup from "json-schema-yup-transformer";
> 
> const schema = {
> type: "object",
> $schema: "http://json-schema.org/draft-07/schema#",
> $id: "example-default-error-messages",
> title: "Example of default error messages",
> properties: {
> items: {
> type: "object",
> nullable: true,
> properties: {
> name: {
> type: "string"
> }
> },
> required: ["name"]
> }
> }
> };
> 
> // set default error message for type of string
> 
> const config = {
> errors: {
> defaults: {
> string: "Custom error message"
> },
> items: {
> name: {
> required: "My Message validacion"
> }
> }
> }
> };
> 
> // check validity
> const yupschema = convertToYup(schema, config);
> let errorMessage;
> 
> try {
> errorMessage = yupschema.validateSync({
> 
> });
> } catch (e) {
> errorMessage = e.errors[0];
> }
> 
> console.log(errorMessage)

@gustavodecarli thanks for raising this issue and sorry for the late response. From what i can see you are trying to validate property (name) exist within an array of objects. I've recreated a working example [here](https://codesandbox.io/s/modest-snowflake-ret2p?file=/src/index.js). Let me know if you need any further clarification.
