### ISSUE TITLE
Conditional in object.

### ISSUE THREAD

**Issue by gustavodecarli** [ritchieanesco/json-schema-yup-transform#37]
It is posible ?

if: {
        properties: { consent: { properties : { value : { const: true } } }}
      },

Thank ?

**Comment by gustavodecarli** [comment]
send the test. thank 

import * as Yup from "yup";
import { JSONSchema7 } from "json-schema";
import convertToYup from "../../src";

describe("convertToYup() object conditions", () => {
  it("should validate all fields with exception to conditional fields", () => {
    const schema: JSONSchema7 = {
      type: "object",
      $schema: "http://json-schema.org/draft-07/schema#",
      $id: "test",
      title: "Test",
      properties: {
        consent: {
          type: "object",
          properties : {
            value : {
              type : "integer"
            }
          }
        }
      },
      required: ["consent"],
      if: {
        properties:  { consent: { properties : { value : { const: 1 } } } } 
      },
      then: {
        properties: {
          phone: { type: "number" }
        }
      }
    };
    const yupschema = convertToYup(schema) as Yup.ObjectSchema;

    let isValid = yupschema.isValidSync({
      consent: { value : 1},
      phone : "333"
    });
    expect(isValid).toBeFalsy();

  });
});

**Comment by ritchieanesco** [comment]
Closing this issue as it seems to be resolved?
