### ISSUE TITLE
Second properties in else conditional

### ISSUE THREAD

**Issue by gustavodecarli** [ritchieanesco/json-schema-yup-transform#52]
Sorry I don't understand why it requires the second property of the else

import * as Yup from "yup";
import { JSONSchema7 } from "json-schema";
import convertToYup from "../../src";

describe("convertToYup() number conditions", () => {

  it("should validate other conditional", () => {
    const schema: JSONSchema7 = {
      type: "object",
      $schema: "http://json-schema.org/draft-07/schema#",
      $id: "test",
      title: "Test",
      properties: {
        mode: {
          type: "string",
          enum: ["C", "E"]
        }
      },
      required: ["type"],
      if: {
        properties: { counmodetry: { type: "string", const: "E" } }
      },
      then: {
        properties: {
          namecorp: {  type: "string"},
          weburl: {  type: "string" }
        },
        required: [
          "namecorp" , "weburl"
        ]
      },
      else: {
        properties: {
          firstname: {  type: "string"},
          lastname : {  type: "string"}
        },
        required: [
          "firstname" , "lastname"
        ]
      }
    };
    const yupschema = convertToYup(schema) as Yup.ObjectSchema;

    const dataC = {
      mode: "E",      
      namecorp: "Micro",
      weburl: "wwww.google.com",
      firstname: undefined,
      lastname : undefined
    }

    const dataE = {
      mode: "C",
      namecorp: undefined,
      weburl: undefined,
      firstname: "Albert",
      lastname : "Einstein"
    }

    try{
      yupschema.validateSync(dataC)
    }catch(error) { 
      console.log('---->', error)
    };
    
    let isValid = yupschema.isValidSync(dataC);

    expect(isValid).toBeTruthy();

    let isValid2 = yupschema.isValidSync(dataE);

    expect(isValid2).toBeTruthy();
  });
});

**Comment by ritchieanesco** [comment]
This has been fixed in  v1.6.6-beta.0. Thanks for raising this issue.
